### ISSUE TITLE
Version dictionary

### ISSUE THREAD

**Issue by JamieMagee** [jeppebundsgaard/stavekontrolden#1]
Is it possible to version the dictionaries that are uploaded to stavekontrolden.dk? i.e. Have `da_DK-2.5.108.dic` instead of just `da_DK.dic`.

I ask because without versioning the dictionary, it's very difficult to maintain Linux packages for the dictionaries. See https://aur.archlinux.org/packages/hunspell-da/

**Comment by jeppebundsgaard** [comment]
Yes, that is possible. I will change the name in the weekend, when I am back from vacation.




Mvh 


Jeppe


Sendt fra mobil. Derfor kortfattet.


---


Jeppe Bundsgaard


+45 31192607







On Thu, Jul 9, 2020 at 9:38 AM +0200, "Jamie Magee" <notifications@github.com> wrote:















Is it possible to version the dictionaries that are uploaded to stavekontrolden.dk? i.e. Have da_DK-2.5.108.dic instead of just da_DK.dic.


I ask because without versioning the dictionary, it's very difficult to maintain Linux packages for the dictionaries. See https://aur.archlinux.org/packages/hunspell-da/

**Comment by jeppebundsgaard** [comment]
Hi again,Now the files have their version number as part of the title
(but if you download them by clicking the link, the browser just uses
the name without version number). Is that okay?Jeppetor, 09 07 2020 kl.
00:38 -0700, skrev Jamie Magee:

**Comment by jeppebundsgaard** [comment]
I removed the behavior where downloading resulted in no-version-number versions. I guess it doesn't make any difference for you, but now you know.

**Comment by JamieMagee** [comment]
@jeppebundsgaard Sorry for not responding. Adding the version number, and keeping the old versions available for download, has made it a lot easier to package these dictionaries for Linux. Thank you!
